import type { EvalCase, RepoContext, RepoFile } from "../types.js";
import type { ReadinessProviderInput } from "./types.js";

const MAX_PROMPT_CHARS = 80_000;
const MAX_FILE_CONTENT_CHARS = 8_000;
const MAX_FILE_LIST = 200;

export function buildAgentResponsePrompt(evalCase: EvalCase, repoContext: RepoContext): string {
  const header = [
    "You are generating an Agent Response for Ghostbench, a repo-understanding eval harness.",
    "",
    "Answer the user's repository task as a coding agent would before making changes.",
    "Be honest about uncertainty. Do not invent files, symbols, APIs, tests, or repository behavior.",
    "Ground your plan in the bounded repo context below. If context is missing or partial, say so.",
    "Keep the plan bounded to the task and call out important edge cases or verification steps.",
    "",
    `Eval case: ${evalCase.title}`,
    `Case id: ${evalCase.id}`,
    "",
    "Task:",
    evalCase.task,
    "",
    `Repo source: ${repoContext.repoSource}`,
    `Resolved repo path: ${repoContext.repoPath}`,
    `Repo context available: ${repoContext.exists ? "yes" : "no"}`,
    `Repo files scanned: ${repoContext.scannedFiles}/${repoContext.totalEligibleFiles}`,
    "",
    "Expected files or areas are advisory, not hidden gold labels:",
    ...(evalCase.expectedFiles.length > 0 ? evalCase.expectedFiles.map((file) => `- ${file}`) : ["- None provided."]),
    "",
    "Repo context file list:",
    ...repoContext.files.slice(0, MAX_FILE_LIST).map((file) => `- ${file.path}${file.truncated ? " (truncated by scanner)" : ""}`),
    "",
    "Included repo context excerpts:",
  ].join("\n");

  return addFileExcerpts(header, repoContext.files);
}

export function buildReadinessReviewPrompt(input: ReadinessProviderInput): string {
  const header = [
    "You are reviewing a repository readiness assessment generated by Ghostbench.",
    "",
    "Return only valid JSON with this exact shape:",
    "{",
    '  "summary": "one concise paragraph",',
    '  "evidence": ["specific repository-grounded evidence"],',
    '  "concerns": ["specific repository-grounded concern"],',
    '  "recommendations": ["concrete next action"]',
    "}",
    "",
    "Do not invent files, commands, product behavior, APIs, or test results.",
    "If the scanned context is partial, phrase claims as limited to the available context.",
    "Use the deterministic Ghostbench assessment as input, but call out any gaps or weak assumptions you see.",
    "",
    `Assessment title: ${input.title}`,
    `Repository path: ${input.repoPath}`,
    `Brief source: ${input.briefSource}`,
    `Execution policy: ${input.executionPolicy}`,
    `Deterministic verdict: ${input.deterministicVerdict}`,
    `Deterministic score: ${input.deterministicScore}/10`,
    "",
    "App brief:",
    input.appBrief || "No app brief supplied.",
    "",
    "Expected areas:",
    ...(input.expectedAreas.length > 0 ? input.expectedAreas.map((area) => `- ${area}`) : ["- None provided."]),
    "",
    "Framework signals:",
    ...(input.frameworkSignals.length > 0
      ? input.frameworkSignals.map((signal) => `- ${signal.name}: ${signal.evidence}`)
      : ["- None detected."]),
    "",
    "Script inventory:",
    `- Package manager: ${input.scriptInventory.packageManager}`,
    ...Object.entries(input.scriptInventory.scripts).map(([name, command]) => `- ${name}: ${command}`),
    "",
    "Execution checks:",
    ...input.executionChecks.map((check) => `- ${check.name}: ${check.status} (${check.command}) ${firstLine(check.output)}`),
    "",
    "Dimension scores:",
    ...input.dimensions.map((dimension) => {
      const concern = dimension.concerns[0] ? ` Concern: ${dimension.concerns[0]}` : "";
      return `- ${dimension.name}: ${dimension.score}/10.${concern}`;
    }),
    "",
    "Deterministic concerns:",
    ...(input.deterministicConcerns.length > 0 ? input.deterministicConcerns.map((concern) => `- ${concern}`) : ["- None."]),
    "",
    "Deterministic evidence:",
    ...(input.deterministicEvidence.length > 0 ? input.deterministicEvidence.slice(0, 20).map((evidence) => `- ${evidence}`) : ["- None."]),
    "",
    `Repo source: ${input.repoContext.repoSource}`,
    `Repo context available: ${input.repoContext.exists ? "yes" : "no"}`,
    `Repo files scanned: ${input.repoContext.scannedFiles}/${input.repoContext.totalEligibleFiles}`,
    "",
    "Repo context file list:",
    ...input.repoContext.files.slice(0, MAX_FILE_LIST).map((file) => `- ${file.path}${file.truncated ? " (truncated by scanner)" : ""}`),
    "",
    "Included repo context excerpts:",
  ].join("\n");

  return addFileExcerpts(header, input.repoContext.files);
}

function addFileExcerpts(header: string, files: RepoFile[]): string {
  let prompt = header;
  let remaining = MAX_PROMPT_CHARS - prompt.length;

  if (files.length === 0) {
    return `${prompt}\n\nNo files were available in repo context.\n`;
  }

  for (const file of files) {
    if (remaining <= 0) {
      break;
    }

    const content = file.content.slice(0, Math.min(MAX_FILE_CONTENT_CHARS, Math.max(0, remaining - 200)));
    if (content.length === 0) {
      break;
    }

    const block = [
      "",
      `--- ${file.path}${file.truncated ? " (scanner truncated file)" : ""} ---`,
      "```",
      content,
      "```",
    ].join("\n");

    if (block.length > remaining) {
      prompt += `${block.slice(0, Math.max(0, remaining - 80))}\n...[prompt truncated]\n`;
      remaining = 0;
      break;
    }

    prompt += block;
    remaining = MAX_PROMPT_CHARS - prompt.length;
  }

  if (files.length > 0 && remaining <= 0) {
    prompt += "\n\nAdditional repo context omitted due to prompt size limits.\n";
  }

  return `${prompt}\n`;
}

function firstLine(value: string): string {
  const first = value.split(/\r?\n/).find((line) => line.trim().length > 0);
  return first ? first.slice(0, 240) : "";
}
